name: All Checks

on: [push, pull_request]

jobs:
  build-hal:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        feature: ["imxrt1062"]
    steps:
    - uses: actions/checkout@v2
    - name: Build imxrt-hal for (${{ matrix.feature }}) HAL
      run: cd imxrt-hal && cargo build --verbose --features ${{ matrix.feature }}
    - name: Run tests (${{ matrix.feature }}) for HAL
      run: cd imxrt-hal && cargo test --verbose --features ${{ matrix.feature }}
    - name: Check format (${{ matrix.feature }}) for HAL
      run: cd imxrt-hal && cargo fmt --all -- --check
    - name: Run clippy (${{ matrix.feature }}) for HAL
      run: cd imxrt-hal && cargo clippy --features ${{ matrix.feature }} -- -D warnings
